
export const IataData = [
    { code: "FAO", location: "Faro, Portugal" },
    { code: "HER", location: "Heraklion, Greece" },
    { code: "DSS", location: "Dakar, Senegal" },
    { code: "SID", location: "Sal, Cape Verde" },
    { code: "ZTH", location: "Zakynthos, Greece" },
    { code: "PFO", location: "Paphos, Cyprus" },
    { code: "NCE", location: "Nice, France" },
    { code: "PDL", location: "Ponta Delgada, Portugal" },
    { code: "TFS", location: "Tenerife, Spain" },
    { code: "TBS", location: "Tbilisi, Georgia" },
    { code: "PMI", location: "Palma de Mallorca, Spain" },
    { code: "SPU", location: "Split, Croatia" },
    { code: "ALC", location: "Alicante, Spain" },
    { code: "KEF", location: "Reykjavik, Iceland" },
    { code: "IBZ", location: "Ibiza, Spain" },
    { code: "OPO", location: "Porto, Portugal" },
    { code: "FUE", location: "Fuerteventura, Spain" },
    { code: "MIA", location: "Miami, United States" },
    { code: "BOG", location: "Bogotá, Colombia" },
    { code: "LPA", location: "Las Palmas, Spain" },
    { code: "VLC", location: "Valencia, Spain" },
    { code: "RHO", location: "Rhodes, Greece" },
    { code: "LHR", location: "London Heathrow, United Kingdom" },
    { code: "LCA", location: "Larnaca, Cyprus" },
    { code: "ATH", location: "Athens, Greece" },
    { code: "GRO", location: "Girona, Spain" },
    { code: "ADB", location: "Izmir, Turkey" },
    { code: "BCN", location: "Barcelona, Spain" },
    { code: "AGP", location: "Málaga, Spain" },
    { code: "AYT", location: "Antalya, Turkey" },
    { code: "RAK", location: "Marrakech, Morocco" },
    { code: "SPC", location: "La Palma, Spain" },
    { code: "LIS", location: "Lisbon, Portugal" },
    { code: "AOK", location: "Karpathos, Greece" },
    { code: "CTA", location: "Catania, Italy" },
    { code: "SVQ", location: "Seville, Spain" },
    { code: "MJT", location: "Mytilene, Greece" },
    { code: "VNO", location: "Vilnius, Lithuania" },
];